<<<<<<< HEAD
import type { Metadata } from "next";
import "./globals.css";
import {Outfit} from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets: ['latin']});
=======
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";
>>>>>>> 62785052cf75ed507755181a49a430ae1eb9c025

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
<<<<<<< HEAD
        <body
          className= {outfit.className}
        >
          <Provider>
            {children}    
          </Provider>   
          <Toaster />     
        </body>
      </html>
    </ClerkProvider>
    
=======
        <body className='min-h-screen h-screen overflow-hidden flex flex-col'>
          {children}
        </body>
      </html>
    </ClerkProvider>
>>>>>>> 62785052cf75ed507755181a49a430ae1eb9c025
  );
}
